language: cpp
sudo: false
dist: trusty
os:
  - linux

addons:
  apt:
    packages:
      - cmake

before_install:
  - wget http://downloads.arduino.cc/arduino-1.8.3-linux64.tar.xz
  - tar xf arduino-1.8.3-linux64.tar.xz
  - mv arduino-1.8.3 ${TRAVIS_BUILD_DIR}/arduino-1.8.3
  - cp env.travis.cmake env.cmake

script: mkdir -p build && cd build && cmake .. && make arduino-cmake-template.hex
